from abc import ABC, abstractmethod
from typing import Sequence, Tuple

from application.services.acquisition_throughput_characterization_service.dtos.acquisition_parameters_dtos import (
    AcquisitionParametersDTO,
    ExportedFileDTO,
)
from application.services.acquisition_throughput_characterization_service.dtos.acquisition_throughput_dtos import (
    AcquisitionThroughputCharacterizationDTO,
    AcquisitionThroughputSampleDTO,
)
from domain.shared_kernel.operation_result import OperationResult


class IAcquisitionThroughputExportPort(ABC):
    """
    Responsibility:
    - Persist one throughput characterization in its own export location:
      raw samples + summary, and the acquisition parameters (everything that
      influenced the sweep).

    Rationale:
    - The 2024 characterization was lost because it lived in an ad hoc
      spreadsheet; the raw samples must be kept next to the summary so the
      analysis can be redone. On 2026-10-02 two sweeps could not be put back
      in context: the conditions must be written next to the data.

    Design:
    - open_export() at the start of the sweep (the parameters are written
      there while it runs), export() and a final write_acquisition_parameters()
      at the end.
    - export() returns what it wrote (size, SHA-256), handed back in the
      parameters as the files generated by the sweep.
    - The port owns the file format of the parameters: it receives
      format-agnostic DTOs.
    - Expected I/O failures (disk full, no permission) are failures, never
      raised.
    """

    @abstractmethod
    def open_export(self, oversampling_ratio: int, excitation_label: str) -> OperationResult[str, str]:
        """Create the export location; returns it."""

    @abstractmethod
    def export(
        self,
        location: str,
        result: AcquisitionThroughputCharacterizationDTO,
        samples: Sequence[AcquisitionThroughputSampleDTO],
    ) -> OperationResult[Tuple[ExportedFileDTO, ...], str]: ...

    @abstractmethod
    def write_acquisition_parameters(
        self, location: str, parameters: AcquisitionParametersDTO
    ) -> OperationResult[None, str]:
        """(Re)write the acquisition parameters of the sweep in `location`."""
